name: Run Auto Login Daily
on:
  schedule:
    - cron: "55 22 * * *" # UTC 22:55 -> KST 07:55 (next day)
  workflow_dispatch:
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache Playwright Browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13.7"
      - name: Create .env file
        env:
          SLACK_BOT_OAUTH_TOKEN: ${{secrets.SLACK_BOT_OAUTH_TOKEN}}
          SLACK_CHANNEL: ${{secrets.SLACK_CHANNEL}}
          DAEWON_ID: ${{secrets.DAEWON_ID}}
          DAEWON_PW: ${{secrets.DAEWON_PW}}
          SOFRANO_ID: ${{secrets.SOFRANO_ID}}
          SOFRANO_PW: ${{secrets.SOFRANO_PW}}
          PLAYSHOP_ID: ${{secrets.PLAYSHOP_ID}}
          PLAYSHOP_PW: ${{secrets.PLAYSHOP_PW}}
        run: |
          echo "SLACK_BOT_OAUTH_TOKEN=\"$SLACK_BOT_OAUTH_TOKEN\"" >> .env
          echo "SLACK_CHANNEL=\"$SLACK_CHANNEL\"" >> .env
          echo "DAEWON_ID=\"$DAEWON_ID\"" >> .env
          echo "DAEWON_PW=\"$DAEWON_PW\"" >> .env
          echo "SOFRANO_ID=\"$SOFRANO_ID\"" >> .env
          echo "SOFRANO_PW=\"$SOFRANO_PW\"" >> .env
          echo "PLAYSHOP_ID=\"$PLAYSHOP_ID\"" >> .env
          echo "PLAYSHOP_PW=\"$PLAYSHOP_PW\"" >> .env
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install Playwright Browsers
        run: python -m playwright install --with-deps
      - name: Install tesseract
        run: |
          sudo apt update
          sudo add-apt-repository universe
          sudo apt install -y tesseract-ocr
          sudo apt install -y tesseract-ocr-eng
      - name: Run script with env
        run: python main.py
      # - name: Upload Exception Html and Screenshot as artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: exception-files
      #     path: | 
      #       page_source.html
      #       page_screenshot.png
      #       page_console_log.txt
      #     if-no-files-found: ignore